[package]
name = "monster-regex"
description = "A custom regex spec"
version = "0.1.0-alpha.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/monster0506/monster-regex"
documentation = "https://docs.rs/monster-regex"

[dependencies]
